name: Java CI with Gradle

on:
  push:
    branches: [ "arena/01a0cfbf-anthem" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          java-package: 'jdk'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./wyvern-dlc

      - name: Build
        run: ./gradlew build --no-daemon
        working-directory: ./wyvern-dlc

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: compiled-jar
          path: ./wyvern-dlc/build/libs/*.jar
